version: "3"
services:
  web:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://manager:secret@127.0.0.1:3306/symfony
  db:
    image: mariadb:10.3.9
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=manager
      - MYSQL_PASSWORD=secret

volumes:
  data: